log_file: '../Resources/logs/bot.log'

instagram:
  username: '2true_25'
  password: 'change123'

spotify:
  client_id: 'd7bcddda54a848f2b639107aab756d0e'
  client_secret: 'b84e197972bf466f9a8c43fcc069ad56'
  redirect_uri: 'http://localhost:8888/callback'
